### ISSUE TITLE
migrate test from corefx

### ISSUE THREAD

**Issue by dzmitry-lahoda** [manofstick/Cistern.Linq#1]

**Comment by manofstick** [comment]
Definitely the plan!

...but if anyone else is inspired to do it then I would be very happy!

**Comment by dzmitry-lahoda** [comment]
i guess you know that sometimes some edge cases (covered by tests) are broken by optimizations. fixing edge cases may neglect whole optimization done.
sometimes optimization in one cases is deoptimization in another.
so without correctness tests, without performance tests, and without simplistic example of why it faster in readme - doubt project will go somewhere. i guess you will hardly find anybody to do that work. given there are other linq optimization approaches out there.

**Comment by manofstick** [comment]
Maybe you misunderstood me? Of course the plan is to move the tests over, I just have limited time, and any assistance would be appreciated (as it's not just a matter of copying them over, as there are some dependencies etc.)

**Comment by manofstick** [comment]
Tests added in [this commit](https://github.com/manofstick/Cistern.Linq/commit/f592dfe9fd589fe109ca897bb7f06a3bc802c169).

...need to generate some issues from the few failing/ignored tests...
